/*
 * MeMaS APIs
 *
 * This is the Control Plane and Data Plane APIs for MeMaS (Memory Management Service). See https://github.com/memas-ai/MeMaS for more details.
 *
 * The version of the OpenAPI document: 0.1.1
 * Contact: max.yu@memas.ai
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CitedDocument {
    #[serde(rename = "document")]
    pub document: String,
    #[serde(rename = "citation")]
    pub citation: Box<crate::models::Citation>,
}

impl CitedDocument {
    pub fn new(document: String, citation: crate::models::Citation) -> CitedDocument {
        CitedDocument {
            document,
            citation: Box::new(citation),
        }
    }
}


