/*
 * MeMaS CP APIs
 *
 * This is the Control Plane APIs for MeMaS (Memory Management Service).
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: max.yu@memas.ai
 * Generated by: https://openapi-generator.tech
 */

/// CorpusType : Type of a Corpus

/// Type of a Corpus
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CorpusType {
    #[serde(rename = "knowledge")]
    Knowledge,
    #[serde(rename = "conversation")]
    Conversation,

}

impl ToString for CorpusType {
    fn to_string(&self) -> String {
        match self {
            Self::Knowledge => String::from("knowledge"),
            Self::Conversation => String::from("conversation"),
        }
    }
}

impl Default for CorpusType {
    fn default() -> CorpusType {
        Self::Knowledge
    }
}




