/*
 * MeMaS CP APIs
 *
 * This is the Control Plane APIs for MeMaS (Memory Management Service).
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: max.yu@memas.ai
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateCorpusRequest {
    /// full corpus name
    #[serde(rename = "corpus_pathname", skip_serializing_if = "Option::is_none")]
    pub corpus_pathname: Option<String>,
    #[serde(rename = "corpus_type", skip_serializing_if = "Option::is_none")]
    pub corpus_type: Option<crate::models::CorpusType>,
}

impl CreateCorpusRequest {
    pub fn new() -> CreateCorpusRequest {
        CreateCorpusRequest {
            corpus_pathname: None,
            corpus_type: None,
        }
    }
}


