/*
 * MeMaS CP APIs
 *
 * This is the Control Plane client for MeMaS (Memory Management Service).  See https://github.com/memas-ai/MeMaS for more details.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: max.yu@memas.ai
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateUserRequest {
    /// Full namespace name, where child namespaces are appended after their parents' names with '.'
    #[serde(rename = "namespace_pathname")]
    pub namespace_pathname: String,
}

impl CreateUserRequest {
    pub fn new(namespace_pathname: String) -> CreateUserRequest {
        CreateUserRequest {
            namespace_pathname,
        }
    }
}


