/*
 * MeMaS CP APIs
 *
 * This is the Control Plane client for MeMaS (Memory Management Service).  See https://github.com/memas-ai/MeMaS for more details.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: max.yu@memas.ai
 * Generated by: https://openapi-generator.tech
 */

/// NamespaceDoesNotExistError : Error returned when the namespace object (corpus/user) does not exist



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NamespaceDoesNotExistError {
    #[serde(rename = "error_code")]
    pub error_code: ErrorCode,
    #[serde(rename = "msg")]
    pub msg: String,
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,
}

impl NamespaceDoesNotExistError {
    /// Error returned when the namespace object (corpus/user) does not exist
    pub fn new(error_code: ErrorCode, msg: String) -> NamespaceDoesNotExistError {
        NamespaceDoesNotExistError {
            error_code,
            msg,
            details: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ErrorCode {
    #[serde(rename = "namespace_does_not_exist")]
    NamespaceDoesNotExist,
}

impl Default for ErrorCode {
    fn default() -> ErrorCode {
        Self::NamespaceDoesNotExist
    }
}

